version: "1.1"
name: sum
env:
  host: http://localhost:8080
tests:
  example:
    steps:
      - name: GET request
        http:
          url: ${{env.host}}/api/sum?input1=1&input2=8
          method: GET
          check:
            status: 200
            jsonpath:
              $.sum: 9